# .travis.yml for faskally packages

warnings_are_errors: false

os:
  - linux

language: r
r:
  - release

sudo: false

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - rmarkdown

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
